### PR TITLE
Introduce basic admin screen for managing "Rules Collection" and "Suggested Fields"

### PR DESCRIPTION
**Pull request by epugh**
I am looking at how we can make it easier to add new Solr Collections to SMUI for organizations that have lots of webshops.   This is a very much draft WIP just to help me learn how to write code!

### CODE REVIEW

**Comment by epugh** [comment]
Baby steps:
image

**Comment by epugh** [comment]
image

**Comment by epugh** [comment]
Okay, I think I'm now done ;-)  @pbartusch  I'd love your review on this.   Maybe we need to set up a time and chat?

**Comment by xaviersanchez** [comment]
This looks really useful for customers like us who are starting to use SMUI and need to open the role of searchandizer. Anything that helps managing the collections from the Admin is a huge plus!

**Comment by pbartusch** [comment]
Hi @xaviersanchez , I agree , the feature is helpful in general. @epugh : Thanks for sharing the effort with this PR.

Just as a note: other clients use the API and ensure in the deployment routine , that the expected deployment channels are present - that might be an attractive alternative , as it works automatically (deployment channels are usually tight to the index structure, and therefore a likely concern to the Search Dev team).

@epugh : The PR is extensive , just as a quick feedback:

*Critical:*

Deleting a deployment channel (a.k.a `SolrIndex`) is a critical operation. Maintained rules as well as history items can loose references:

```
def delete(id: String)(implicit connection: Connection): Int = {
  SQL"delete from #$TABLE_NAME where id = $id".executeUpdate()
}

(In `app/models/SolrIndex.scala`)
```

It should at least be checked, that a deleted deployment channel is empty.

*Other:*

* With the split of backend and frontend, new UI features should be tested in SMUI (e2e-test) to ensure backwards compatibility. I haven't found a frontend test for the admin feature.
* Deletion of a SuggestedField not tested (e.g. test/models/SuggestedSolrFieldSpec.scala).
* One further UX note: Creation of a new deployment channel seems not to be reflected in the upper-right channel selection menu (unless manually reloaded).

**Comment by pbartusch** [comment]
Just a side note (hint , @epugh ) : when I build SMUI today (sbt docker) it seemed, that the repo location for sbt from debian is not available any more :-( I updated the dependency with branch `fix_build_in_3_13_0`.

Hope , that'll save you some time.

**Comment by epugh** [comment]
I wonder if we need a confirmation button on the delete of a Rules Collection, that mentions that it is in use...?  Maybe a more custom warning like "Are you sure you want to delete Spanish webshop, it has X rules"

**Comment by epugh** [comment]
> _Critical:_
> 
> Deleting a deployment channel (a.k.a `SolrIndex`) is a critical operation. Maintained rules as well as history items can loose references:

This is now Done!  I added checks at the `SolrRepostoryManager` level


> 
>     * Deletion of a SuggestedField not tested (e.g. test/models/SuggestedSolrFieldSpec.scala).

Done!

**Comment by epugh** [comment]
>     * With the split of backend and frontend, new UI features should be tested in SMUI (e2e-test) to ensure backwards compatibility. I haven't found a frontend test for the admin feature.

Check out `spec/admin.js` which tests out the logic for creating a rules collection!   I had to kind of hack things to make it run, like change the base port to 4200, and remove the reference to `pg`, which is because I am running SMUI locally, not in docker.    I am still going to add a test for the Deployment Channel (Rules Collection?) drop down, it WAS working, so great catch!

**Comment by epugh** [comment]
I've retested, and now the drop down does populate when you create new rows.

**Pull request merged**
