### PR TITLE
Introduce users and teams for managing access to various Rules Collections ;-)

### PR DESCRIPTION
**Pull request by epugh**
Now that we are tracking user info changes, and have an Admin interface, this PR is targeting adding a `controllers.auth.UsernamePasswordAuthenticatedAction`, and the relate database tables.  

I aim to make this live alongside the existing authentication mechanisms...    When you log in, you have access to specific Rules Collections.   

And then in a follow up PR, to enable OIDC (OpenID?) authentication, similar to how we do it with Quepid.   Support Keycloak and Google Auth maybe to start with?

### CODE REVIEW

**Comment by epugh** [comment]
image

image

**Comment by epugh** [comment]
@pbartusch we have a new branch that wraps this work up that is MUCH better, so closing this PR ;-).

**Comment by pbartusch** [comment]
@epugh , alright. Where is this branch located?

**Comment by epugh** [comment]
https://github.com/o19s/smui/tree/work_on_admin_screens_for_teams    @Paul-Blanchaert has done some really great work on it!

**Pull request closed without merging**
